@baseUrl = http://localhost:8080/api/v1

@urlHeroku = https://s-test-react-travel-blog-api-210021db115a.herokuapp.com/api/v1


### GET all posts
GET {{baseUrl}}/posts

### GET all posts from Heroku
GET {{urlHeroku}}/posts

### Gets a single post
@postIdToGet = 6845b850a826b219b82a2352
GET {{baseUrl}}/posts/{{postIdToGet}}

### Add a new post
POST {{baseUrl}}/posts
Content-Type: application/json

{
  "title": "Hamburg – Ice Baths and Cheesecake",
  "authorId": "6845bb48ad694ea9e6f31dd0",
  "location": {
    "city": "Hamburg",
    "country": "Germany",
    "lng": "9.921828561927141",
    "lat": "53.554197560299826"
  },
  "description": "My Hamburg: A city to breathe, discover and enjoy – from the river to the best cheesecake in town.",
  "summary": "Hamburg is a city close to my heart – vibrant, diverse, and calming at the same time. My favorite place is Elbstrand, where the water and tides ground me and help me unwind. In winter, I join the \"Eisbademeisters\" for cold water swims – the group energy is amazing, and nothing beats warming up afterward with a hot coffee at the Ahoi Kiosk. That’s my Saturday ritual. I love exploring the city's many neighborhoods – Ottensen, Schanze, and St. Pauli all have their own vibe. Hamburg is full of unique cafés, and I could sit in a different one every day. The best cheesecake? You'll find it near the city park at Jeff’s Cheesecake – absolutely dreamy. Hamburg never gets boring and always has something new to offer. Always worth a trip.",
  "date": "2024-03-02",
  "thumbnail": "/img/hamburg-1-thumbnail.jpg",
  "image": "/img/hamburg-1.jpg"
}

### Deletes the new post above - Change the id manualy
@postIdToDelete = 6854060328d2bbd0f8a72b5c
DELETE {{baseUrl}}/posts/{{postIdToDelete}}

  
